# Generated by Django 3.2.5 on 2021-07-13 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_uuid_resume_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
