# Generated by Django 3.2.5 on 2021-07-13 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=5000, verbose_name='Описание')),
                ('work_experience', models.CharField(choices=[('ETR', 'Без опыта'), ('MID', '1-3 год'), ('SR', 'от 3 и более лет')], max_length=20, verbose_name='Опыт работы')),
                ('type_job', multiselectfield.db.fields.MultiSelectField(choices=[('RM', 'Удалённая работа'), ('FT', 'Полная занятость'), ('PTE', 'Частичная занятость')], max_length=9, verbose_name='Формат работы')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124, verbose_name='Навык')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='vacancies.vacancy', verbose_name='Вакансия')),
            ],
        ),
    ]
