# Generated by Django 3.2.5 on 2021-07-15 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=5000, verbose_name='Описание')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Зарплата')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Страна/Город')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес')),
                ('work_experience', models.CharField(choices=[('Без опыта', 'Без опыта'), ('1-3 год', '1-3 год'), ('от 3 и более лет', 'от 3 и более лет')], max_length=20, verbose_name='Опыт работы')),
                ('type_job', multiselectfield.db.fields.MultiSelectField(choices=[('Удалённая работа', 'Удалённая работа'), ('Полная занятость', 'Полная занятость'), ('Частичная занятость', 'Частичная занятость')], max_length=53, verbose_name='Формат работы')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to=settings.AUTH_USER_MODEL, verbose_name='Работодатель')),
                ('responding', models.ManyToManyField(related_name='my_vacancies', through='users.UserVacancyRelation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124, verbose_name='Навык')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='vacancies.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
            },
        ),
    ]
