# Generated by Django 3.2.5 on 2021-07-13 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0004_alter_vacancy_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Зарплата'),
        ),
        migrations.CreateModel(
            name='UserVacancyRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_bookmarks', models.BooleanField(verbose_name='Избранное')),
                ('in_response', models.BooleanField(verbose_name='Отклик')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='vacancies.vacancy', verbose_name='Вакансия')),
            ],
        ),
    ]
