# Generated by Django 3.2.5 on 2021-07-13 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_auto_20210713_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uservacancyrelation',
            options={'verbose_name': 'Закладки и отклики', 'verbose_name_plural': 'Закладки и отклики'},
        ),
    ]
