# Generated by Django 3.2.5 on 2021-07-13 16:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_uservacancyrelation'),
        ('vacancies', '0006_alter_uservacancyrelation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Страна/Город'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='responding',
            field=models.ManyToManyField(related_name='my_vacancies', through='users.UserVacancyRelation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.DeleteModel(
            name='UserVacancyRelation',
        ),
    ]
